version: '3.1'

services: 
  maze:
    build: ./maze
    ports: 
      -50052:50051
    environment: 
      URL: "datastore:27017"
      POST: "4900"
  datastore:
    image: mongo
    ports:
      - 27017:27017S